name: CEST

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Test Loader
      run: |
        cd Loader
        pytest
        cd ..
    - name: Test CEST
      run: |
        cd CEST
        pytest
        cd ..
    - name: Test Metrics
      run: |
        cd Metrics
        pytest
        cd ..
    - name: Test Transform
      run: |
        cd Transform
        pytest
        cd ..
